version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/db/postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data
      
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      
volumes:
  db-data: