# Generated by Django 4.1.4 on 2023-01-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='latin_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='name',
            field=models.CharField(default='undefined', max_length=60),
            preserve_default=False,
        ),
    ]
