# Generated by Django 4.1.4 on 2023-01-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funga', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/db/post/img/post10.png', upload_to='db/post/img/'),
            preserve_default=False,
        ),
    ]
